services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: LaskoDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./SQL/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d LaskoDB"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s
    networks:
      - lasko-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DEBUG: "1"
      DJANGO_SETTINGS_MODULE: lasko_backend.settings
      POSTGRES_DB: LaskoDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: "5432"
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        python manage.py check_db_ready &&
        echo 'Applying migrations...' &&
        python manage.py migrate --noinput --fake-initial &&
        echo 'Seeding (custom setup)...' &&
        python manage.py setup_database --with-seed || true &&
        echo 'Starting server...' &&
        python manage.py runserver 0.0.0.0:8000
      "
    # Healthcheck: sprawdzamy tylko, czy port 8000 nasłuchuje (szybciej i stabilniej)
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 8000 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 60
      start_period: 30s
    networks:
      - lasko-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/lasko-frontend
    environment:
      VITE_API_BASE_URL: http://backend:8000
      NODE_ENV: development
    volumes:
      - ./frontend/lasko-frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started   # backend musi wystartować, niekoniecznie od razu być 'healthy' HTTP
    networks:
      - lasko-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  lasko-network:
    driver: bridge
